export class Constants {
	public homeSectionLinksId = {
		WORK_EXPERIENCE: 'WORK-EXPERIENCE',
		SKILLS: 'SKILLS',
		PERSONAL_PROJECTS: 'PERSONAL-PROJECTS',
		EDUCATION: 'EDUCATION',
		ACHIEVEMENTS: 'ACHIEVEMENTS',
		AWARDS_AND_CERTIFICATIONS: 'AWARDS-AND-CERTIFICATIONS',
		CODING_AND_SOCIAL_PROFILES: 'CODING-AND-SOCIAL-PROFILES',
	};
}
